# Generated by Django 6.0.5 on 2026-05-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='purpose',
            field=models.TextField(blank=True, default=''),
        ),
    ]
