# Generated by Django 6.0.5 on 2026-05-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='purpose',
            field=models.TextField(default=''),
        ),
    ]
