--
-- PostgreSQL database dump
--

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: rhen
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO rhen;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: rhen
--

COMMENT ON SCHEMA public IS '';


--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


--
-- Name: decision_type; Type: TYPE; Schema: public; Owner: rhen
--

CREATE TYPE public.decision_type AS ENUM (
    'approved',
    'rejected'
);


ALTER TYPE public.decision_type OWNER TO rhen;

--
-- Name: requester_role; Type: TYPE; Schema: public; Owner: rhen
--

CREATE TYPE public.requester_role AS ENUM (
    'student',
    'teacher'
);


ALTER TYPE public.requester_role OWNER TO rhen;

--
-- Name: reservation_status; Type: TYPE; Schema: public; Owner: rhen
--

CREATE TYPE public.reservation_status AS ENUM (
    'pending',
    'approved',
    'rejected',
    'cancelled'
);


ALTER TYPE public.reservation_status OWNER TO rhen;

--
-- Name: reservation_type; Type: TYPE; Schema: public; Owner: rhen
--

CREATE TYPE public.reservation_type AS ENUM (
    'class',
    'event'
);


ALTER TYPE public.reservation_type OWNER TO rhen;

--
-- Name: room_type; Type: TYPE; Schema: public; Owner: rhen
--

CREATE TYPE public.room_type AS ENUM (
    'classroom',
    'lab',
    'conference',
    'multipurpose'
);


ALTER TYPE public.room_type OWNER TO rhen;

--
-- Name: user_role; Type: TYPE; Schema: public; Owner: rhen
--

CREATE TYPE public.user_role AS ENUM (
    'student',
    'teacher',
    'ict'
);


ALTER TYPE public.user_role OWNER TO rhen;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_user; Type: TABLE; Schema: public; Owner: rhen
--

CREATE TABLE public.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    role character varying(20) NOT NULL
);


ALTER TABLE public.accounts_user OWNER TO rhen;

--
-- Name: accounts_user_groups; Type: TABLE; Schema: public; Owner: rhen
--

CREATE TABLE public.accounts_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.accounts_user_groups OWNER TO rhen;

--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: rhen
--

ALTER TABLE public.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: rhen
--

ALTER TABLE public.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_user_permissions; Type: TABLE; Schema: public; Owner: rhen
--

CREATE TABLE public.accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.accounts_user_user_permissions OWNER TO rhen;

--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: rhen
--

ALTER TABLE public.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: approvals; Type: TABLE; Schema: public; Owner: rhen
--

CREATE TABLE public.approvals (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    reservation_id uuid NOT NULL,
    approver_id uuid NOT NULL,
    decision public.decision_type NOT NULL,
    remarks text,
    decided_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.approvals OWNER TO rhen;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: rhen
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO rhen;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: rhen
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: rhen
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO rhen;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: rhen
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: rhen
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO rhen;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: rhen
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: rhen
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO rhen;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: rhen
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: rhen
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO rhen;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: rhen
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: rhen
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO rhen;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: rhen
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: rhen
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO rhen;

--
-- Name: ict_staff; Type: TABLE; Schema: public; Owner: rhen
--

CREATE TABLE public.ict_staff (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    employee_id character varying(100) NOT NULL,
    "position" character varying(255),
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.ict_staff OWNER TO rhen;

--
-- Name: notifications; Type: TABLE; Schema: public; Owner: rhen
--

CREATE TABLE public.notifications (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    reservation_id uuid NOT NULL,
    message text NOT NULL,
    is_read boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.notifications OWNER TO rhen;

--
-- Name: notifications_notification; Type: TABLE; Schema: public; Owner: rhen
--

CREATE TABLE public.notifications_notification (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    message text NOT NULL,
    is_read boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    notif_type character varying(50) NOT NULL,
    reservation_id bigint
);


ALTER TABLE public.notifications_notification OWNER TO rhen;

--
-- Name: notifications_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: rhen
--

ALTER TABLE public.notifications_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservation_policy; Type: TABLE; Schema: public; Owner: rhen
--

CREATE TABLE public.reservation_policy (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    reservation_type public.reservation_type NOT NULL,
    allowed_role public.requester_role NOT NULL,
    description text
);


ALTER TABLE public.reservation_policy OWNER TO rhen;

--
-- Name: reservations; Type: TABLE; Schema: public; Owner: rhen
--

CREATE TABLE public.reservations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    requester_id uuid NOT NULL,
    room_id uuid NOT NULL,
    reservation_type public.reservation_type NOT NULL,
    requester_role public.requester_role NOT NULL,
    purpose text,
    expected_attendees integer,
    reservation_date date NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    status public.reservation_status DEFAULT 'pending'::public.reservation_status,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.reservations OWNER TO rhen;

--
-- Name: reservations_reservation; Type: TABLE; Schema: public; Owner: rhen
--

CREATE TABLE public.reservations_reservation (
    id bigint NOT NULL,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    room_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.reservations_reservation OWNER TO rhen;

--
-- Name: reservations_reservation_id_seq; Type: SEQUENCE; Schema: public; Owner: rhen
--

ALTER TABLE public.reservations_reservation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservations_reservation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: room_amenities; Type: TABLE; Schema: public; Owner: rhen
--

CREATE TABLE public.room_amenities (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    room_id uuid NOT NULL,
    amenity_name character varying(255) NOT NULL,
    description text
);


ALTER TABLE public.room_amenities OWNER TO rhen;

--
-- Name: rooms; Type: TABLE; Schema: public; Owner: rhen
--

CREATE TABLE public.rooms (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    room_code character varying(50) NOT NULL,
    room_name character varying(255) CONSTRAINT rooms_room_name_not_null1 NOT NULL,
    building character varying(255),
    floor_number integer,
    capacity integer,
    room_type public.room_type NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.rooms OWNER TO rhen;

--
-- Name: rooms_room; Type: TABLE; Schema: public; Owner: rhen
--

CREATE TABLE public.rooms_room (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    capacity integer NOT NULL,
    location character varying(100) NOT NULL,
    description text NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.rooms_room OWNER TO rhen;

--
-- Name: rooms_room_id_seq; Type: SEQUENCE; Schema: public; Owner: rhen
--

ALTER TABLE public.rooms_room ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rooms_room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teachers; Type: TABLE; Schema: public; Owner: rhen
--

CREATE TABLE public.teachers (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    employee_id character varying(100) NOT NULL,
    department character varying(255),
    designation character varying(255),
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.teachers OWNER TO rhen;

--
-- Name: users; Type: TABLE; Schema: public; Owner: rhen
--

CREATE TABLE public.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    full_name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    password_hash text NOT NULL,
    role public.user_role NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.users OWNER TO rhen;

--
-- Data for Name: accounts_user; Type: TABLE DATA; Schema: public; Owner: rhen
--

COPY public.accounts_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role) FROM stdin;
4	pbkdf2_sha256$1200000$6xZhkBjcudqJTVWpIfsrCS$zL9VDZeK2JHd+ZgZcyboAR50GoQchCYdMCNUL0Jg/zU=	\N	f	2023-00123-SR-0			student1@pup.com	f	t	2026-05-21 15:35:37.542548+08	student
5	pbkdf2_sha256$1200000$45cds59pJVGSlRamY2o4P5$M17MZf2dVNGTgm3UmnQ2Ips0xeCljW7YLZ+uVUYV+Lo=	\N	f	Edmigail			edmibenjie@gmail.com	f	t	2026-05-21 16:29:18.730805+08	student
6	pbkdf2_sha256$1200000$hmGKD7mj0G3APz0c6fYXkT$P8eIt17B8Cs4hNXIrny5Pgerv3CmDHc8tCcH8bGNWhg=	\N	f	matt			matt@gmail.com	f	t	2026-05-21 16:40:34.207937+08	student
7	pbkdf2_sha256$1200000$bwOGFy9giSZ5sOtHrcyuQB$SvlpOseRoDoXjoRsduxQyyBRbQ7rboRT8Uu+7Nu8PPs=	\N	f	edmigail			edmibenjie@gmail.com	f	t	2026-05-27 10:41:55.5574+08	student
3	pbkdf2_sha256$1200000$NB3ezoAP6UkNUAmMBhWqGy$1Vduu3iLokcMaOFiBbV8kLwwsTVL+//Aa4LECHRB5GA=	2026-05-27 15:09:48.077559+08	t	admin1			admin1@pup.com	t	t	2026-05-21 15:31:08.433143+08	admin
\.


--
-- Data for Name: accounts_user_groups; Type: TABLE DATA; Schema: public; Owner: rhen
--

COPY public.accounts_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: accounts_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: rhen
--

COPY public.accounts_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: approvals; Type: TABLE DATA; Schema: public; Owner: rhen
--

COPY public.approvals (id, reservation_id, approver_id, decision, remarks, decided_at) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: rhen
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: rhen
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: rhen
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_user
22	Can change user	6	change_user
23	Can delete user	6	delete_user
24	Can view user	6	view_user
25	Can add reservation	7	add_reservation
26	Can change reservation	7	change_reservation
27	Can delete reservation	7	delete_reservation
28	Can view reservation	7	view_reservation
29	Can add room	8	add_room
30	Can change room	8	change_room
31	Can delete room	8	delete_room
32	Can view room	8	view_room
33	Can add notification	9	add_notification
34	Can change notification	9	change_notification
35	Can delete notification	9	delete_notification
36	Can view notification	9	view_notification
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: rhen
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
3	2026-05-21 16:06:25.081575+08	1	Room 101	1	[{"added": {}}]	8	3
4	2026-05-21 16:17:27.031533+08	2	Room 102	1	[{"added": {}}]	8	3
5	2026-05-21 16:17:34.867187+08	2	Room 102	2	[]	8	3
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: rhen
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	accounts	user
7	reservations	reservation
8	rooms	room
9	notifications	notification
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: rhen
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-05-21 13:38:05.226777+08
2	contenttypes	0002_remove_content_type_name	2026-05-21 13:38:05.246868+08
3	auth	0001_initial	2026-05-21 13:38:05.316523+08
4	auth	0002_alter_permission_name_max_length	2026-05-21 13:38:05.324145+08
5	auth	0003_alter_user_email_max_length	2026-05-21 13:38:05.330228+08
6	auth	0004_alter_user_username_opts	2026-05-21 13:38:05.336799+08
7	auth	0005_alter_user_last_login_null	2026-05-21 13:38:05.349986+08
8	auth	0006_require_contenttypes_0002	2026-05-21 13:38:05.352127+08
9	auth	0007_alter_validators_add_error_messages	2026-05-21 13:38:05.360389+08
10	auth	0008_alter_user_username_max_length	2026-05-21 13:38:05.367293+08
11	auth	0009_alter_user_last_name_max_length	2026-05-21 13:38:05.37497+08
12	auth	0010_alter_group_name_max_length	2026-05-21 13:38:05.385924+08
13	auth	0011_update_proxy_permissions	2026-05-21 13:38:05.393302+08
14	auth	0012_alter_user_first_name_max_length	2026-05-21 13:38:05.401491+08
15	accounts	0001_initial	2026-05-21 13:38:05.493842+08
16	admin	0001_initial	2026-05-21 13:38:05.552506+08
17	admin	0002_logentry_remove_auto_add	2026-05-21 13:38:05.562131+08
18	admin	0003_logentry_add_action_flag_choices	2026-05-21 13:38:05.572029+08
19	rooms	0001_initial	2026-05-21 13:38:05.589744+08
20	reservations	0001_initial	2026-05-21 13:38:05.629537+08
21	reservations	0002_alter_reservation_status	2026-05-21 13:38:05.641794+08
22	reservations	0003_alter_reservation_status	2026-05-21 13:38:05.657791+08
23	notifications	0001_initial	2026-05-21 13:38:05.690323+08
24	notifications	0002_notification_notif_type_notification_reservation	2026-05-21 13:38:05.722804+08
25	sessions	0001_initial	2026-05-21 13:38:05.739238+08
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: rhen
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
v6ff3cw80i03487ka9h1h1f3evbx045n	.eJxVjDEOwjAMRe-SGUVtXDvAyM4ZKieOSQElUtNOiLtDpQ6w_vfef5mR1yWPa0vzOIk5GzCH3y1wfKSyAblzuVUba1nmKdhNsTtt9lolPS-7-3eQueVv7bqeKHJSOLqUMCgOThA0egoMvZA4YSegqoxDx55d9CcKAciLIJr3B_7rOLk:1wPxsl:IRoPMg81bMPEWImLe_1PmtjHWdzYUZ1UHiOfOI6wgME	2026-06-04 15:31:51.06861+08
plzp4sdlm6bogoaeafb3m24phal7vgks	.eJxVjDEOwjAMRe-SGUVtXDvAyM4ZKieOSQElUtNOiLtDpQ6w_vfef5mR1yWPa0vzOIk5GzCH3y1wfKSyAblzuVUba1nmKdhNsTtt9lolPS-7-3eQueVv7bqeKHJSOLqUMCgOThA0egoMvZA4YSegqoxDx55d9CcKAciLIJr3B_7rOLk:1wPyP8:2V96aoR9H18LrQWSEPca0yECuUMhdRnK1_QICUsZjmk	2026-06-04 16:05:18.273069+08
spz7oxn9sa7rm3yhh2qrq4k4x8jug3tv	.eJxVjDEOwjAMRe-SGUVtXDvAyM4ZKieOSQElUtNOiLtDpQ6w_vfef5mR1yWPa0vzOIk5GzCH3y1wfKSyAblzuVUba1nmKdhNsTtt9lolPS-7-3eQueVv7bqeKHJSOLqUMCgOThA0egoMvZA4YSegqoxDx55d9CcKAciLIJr3B_7rOLk:1wS8Og:JfSMu4efHuaU38si0cqX9CZGIoUOIijX2NrWWt0eYtE	2026-06-10 15:09:46.723086+08
vtwl2yeg0rj9cv7sxx4krykc5vicpsqq	.eJxVjDEOwjAMRe-SGUVtXDvAyM4ZKieOSQElUtNOiLtDpQ6w_vfef5mR1yWPa0vzOIk5GzCH3y1wfKSyAblzuVUba1nmKdhNsTtt9lolPS-7-3eQueVv7bqeKHJSOLqUMCgOThA0egoMvZA4YSegqoxDx55d9CcKAciLIJr3B_7rOLk:1wS8Oi:8v0K6JQYOHL4W0MJNAMBXP_z7A3BUOxqv9cofjgE6c8	2026-06-10 15:09:48.091841+08
\.


--
-- Data for Name: ict_staff; Type: TABLE DATA; Schema: public; Owner: rhen
--

COPY public.ict_staff (id, user_id, employee_id, "position", created_at) FROM stdin;
\.


--
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: rhen
--

COPY public.notifications (id, user_id, reservation_id, message, is_read, created_at) FROM stdin;
\.


--
-- Data for Name: notifications_notification; Type: TABLE DATA; Schema: public; Owner: rhen
--

COPY public.notifications_notification (id, title, message, is_read, created_at, user_id, notif_type, reservation_id) FROM stdin;
1	Reservation Submitted	Your reservation request is pending approval.	f	2026-05-21 16:10:56.767208+08	4	pending	\N
2	Reservation Updated	Your reservation for Room 101 was approved.	f	2026-05-21 16:16:24.476271+08	4	approved	1
3	Reservation Submitted	Your reservation request is pending approval.	f	2026-05-21 16:30:05.930503+08	5	pending	\N
4	Reservation Updated	Your reservation for Room 102 was rejected.	f	2026-05-21 16:31:50.333015+08	5	rejected	2
5	Reservation Submitted	Your reservation request is pending approval.	f	2026-05-21 16:41:52.005268+08	6	pending	\N
6	Reservation Updated	Your reservation for Room 102 was approved.	f	2026-05-21 16:42:46.973231+08	6	approved	3
7	Reservation Submitted	Your reservation request is pending approval.	f	2026-05-21 17:29:16.849846+08	6	pending	\N
8	Reservation Updated	Your reservation for Room 201 was approved.	f	2026-05-21 17:29:41.872537+08	6	approved	4
9	Reservation Submitted	Your reservation request is pending approval.	f	2026-05-21 17:31:30.104754+08	6	pending	\N
10	Reservation Updated	Your reservation for Room 101 was approved.	f	2026-05-21 17:33:04.620799+08	6	approved	5
11	Reservation Submitted	Your reservation request is pending approval.	f	2026-05-22 15:08:36.597858+08	6	pending	\N
12	Reservation Updated	Your reservation for Room 101 was approved.	f	2026-05-22 15:09:06.495948+08	6	approved	6
13	Reservation Submitted	Your reservation request is pending approval.	f	2026-05-22 15:23:35.726965+08	6	pending	\N
14	Reservation Updated	Your reservation for Room 202 was approved.	f	2026-05-22 16:17:33.021223+08	6	approved	7
15	Reservation Submitted	Your reservation request is pending approval.	f	2026-05-26 09:14:02.317397+08	6	pending	\N
16	Reservation Updated	Your reservation for Room 202 was rejected.	f	2026-05-26 09:15:53.591078+08	6	rejected	8
17	Reservation Submitted	Your reservation request is pending approval.	f	2026-05-27 10:15:59.321351+08	3	pending	\N
18	Reservation Submitted	Your reservation request is pending approval.	f	2026-05-27 10:33:58.426585+08	3	pending	\N
19	Reservation Submitted	Your reservation request is pending approval.	f	2026-05-27 10:40:13.183772+08	3	pending	\N
20	Reservation Submitted	Your reservation request is pending approval.	f	2026-05-27 10:43:09.164663+08	7	pending	\N
21	Reservation Updated	Your reservation for Room 202 was rejected.	f	2026-05-27 10:43:55.272267+08	3	rejected	9
22	Reservation Updated	Your reservation for Room 101 was rejected.	f	2026-05-27 10:43:57.441083+08	3	rejected	10
23	Reservation Updated	Your reservation for Room 201 was rejected.	f	2026-05-27 10:44:01.248888+08	3	rejected	11
24	Reservation Updated	Your reservation for Room 102 was rejected.	f	2026-05-27 10:44:04.15465+08	7	rejected	12
25	Reservation Submitted	Your reservation request is pending approval.	f	2026-05-27 10:46:39.937597+08	7	pending	\N
26	Reservation Updated	Your reservation for Room 102 was rejected.	f	2026-05-27 10:46:51.937726+08	7	rejected	13
27	Reservation Submitted	Your reservation request is pending approval.	f	2026-05-27 10:47:08.773041+08	7	pending	\N
28	Reservation Updated	Your reservation for Room 102 was approved.	f	2026-05-27 10:47:44.031979+08	7	approved	14
29	Reservation Submitted	Your reservation request is pending approval.	f	2026-05-27 10:53:30.860441+08	3	pending	\N
30	Reservation Updated	Your reservation for Room 201 was approved.	f	2026-05-27 10:54:55.82053+08	3	approved	15
31	Reservation Cancelled	Your reservation for Room 201 was cancelled.	f	2026-05-27 10:59:02.932829+08	3	cancelled	\N
32	Reservation Submitted	Your reservation request is pending approval.	f	2026-05-27 15:11:23.929998+08	3	pending	\N
33	Reservation Updated	Your reservation for Room 101 was approved.	f	2026-05-27 15:12:37.423206+08	3	approved	16
34	Reservation Cancelled	Your reservation for Room 101 was cancelled.	f	2026-05-27 15:12:56.164019+08	3	cancelled	\N
\.


--
-- Data for Name: reservation_policy; Type: TABLE DATA; Schema: public; Owner: rhen
--

COPY public.reservation_policy (id, reservation_type, allowed_role, description) FROM stdin;
\.


--
-- Data for Name: reservations; Type: TABLE DATA; Schema: public; Owner: rhen
--

COPY public.reservations (id, requester_id, room_id, reservation_type, requester_role, purpose, expected_attendees, reservation_date, start_time, end_time, status, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: reservations_reservation; Type: TABLE DATA; Schema: public; Owner: rhen
--

COPY public.reservations_reservation (id, start_time, end_time, status, created_at, room_id, user_id) FROM stdin;
1	2026-05-22 01:10:00+08	2026-05-22 02:10:00+08	approved	2026-05-21 16:10:56.751882+08	1	4
2	2026-05-22 00:29:00+08	2026-05-22 00:30:00+08	rejected	2026-05-21 16:30:05.751609+08	2	5
3	2026-05-22 02:00:00+08	2026-05-22 03:00:00+08	approved	2026-05-21 16:41:51.988405+08	2	6
4	2026-05-24 01:28:00+08	2026-05-24 03:28:00+08	approved	2026-05-21 17:29:16.838529+08	3	6
5	2026-05-25 01:31:00+08	2026-05-25 02:31:00+08	approved	2026-05-21 17:31:30.097052+08	1	6
6	2026-05-22 23:08:00+08	2026-05-23 00:08:00+08	approved	2026-05-22 15:08:36.489312+08	1	6
7	2026-05-25 15:23:00+08	2026-05-25 17:23:00+08	approved	2026-05-22 15:23:35.705248+08	4	6
8	2026-05-30 00:00:00+08	2026-06-01 12:00:00+08	rejected	2026-05-26 09:14:02.301643+08	4	6
9	2026-05-29 10:15:00+08	2026-05-30 18:20:00+08	rejected	2026-05-27 10:15:59.129267+08	4	3
10	2026-05-27 10:33:00+08	2026-05-27 12:33:00+08	rejected	2026-05-27 10:33:58.38613+08	1	3
11	2026-05-27 10:39:00+08	2026-05-27 12:39:00+08	rejected	2026-05-27 10:40:13.154495+08	3	3
12	2026-05-27 10:43:00+08	2026-05-27 12:43:00+08	rejected	2026-05-27 10:43:09.14428+08	2	7
13	2026-05-27 10:46:00+08	2026-05-27 11:46:00+08	rejected	2026-05-27 10:46:39.91169+08	2	7
14	2026-05-27 10:46:00+08	2026-05-27 11:01:00+08	approved	2026-05-27 10:47:08.755365+08	2	7
15	2026-05-27 10:53:00+08	2026-05-27 11:01:00+08	cancelled	2026-05-27 10:53:30.842033+08	3	3
16	2026-05-27 15:11:00+08	2026-05-27 16:11:00+08	cancelled	2026-05-27 15:11:23.869248+08	1	3
\.


--
-- Data for Name: room_amenities; Type: TABLE DATA; Schema: public; Owner: rhen
--

COPY public.room_amenities (id, room_id, amenity_name, description) FROM stdin;
\.


--
-- Data for Name: rooms; Type: TABLE DATA; Schema: public; Owner: rhen
--

COPY public.rooms (id, room_code, room_name, building, floor_number, capacity, room_type, is_active, created_at) FROM stdin;
\.


--
-- Data for Name: rooms_room; Type: TABLE DATA; Schema: public; Owner: rhen
--

COPY public.rooms_room (id, name, capacity, location, description, created_at) FROM stdin;
1	Room 101	35	1st Floor		2026-05-21 16:06:25.065278+08
3	Room 201	40	2nd Floor		2026-05-21 17:27:20.39343+08
4	Room 202	45	2nd Floor		2026-05-22 15:09:35.996885+08
2	Room 102	40	1st Floor		2026-05-21 16:17:27.017716+08
\.


--
-- Data for Name: teachers; Type: TABLE DATA; Schema: public; Owner: rhen
--

COPY public.teachers (id, user_id, employee_id, department, designation, created_at) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: rhen
--

COPY public.users (id, full_name, email, password_hash, role, is_active, created_at, updated_at) FROM stdin;
\.


--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rhen
--

SELECT pg_catalog.setval('public.accounts_user_groups_id_seq', 1, false);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rhen
--

SELECT pg_catalog.setval('public.accounts_user_id_seq', 7, true);


--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rhen
--

SELECT pg_catalog.setval('public.accounts_user_user_permissions_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rhen
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rhen
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rhen
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 36, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rhen
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 5, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rhen
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 9, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rhen
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 25, true);


--
-- Name: notifications_notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rhen
--

SELECT pg_catalog.setval('public.notifications_notification_id_seq', 34, true);


--
-- Name: reservations_reservation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rhen
--

SELECT pg_catalog.setval('public.reservations_reservation_id_seq', 16, true);


--
-- Name: rooms_room_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rhen
--

SELECT pg_catalog.setval('public.rooms_room_id_seq', 4, true);


--
-- Name: accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: accounts_user accounts_user_username_key; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_username_key UNIQUE (username);


--
-- Name: approvals approvals_pkey; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.approvals
    ADD CONSTRAINT approvals_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: ict_staff ict_staff_employee_id_key; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.ict_staff
    ADD CONSTRAINT ict_staff_employee_id_key UNIQUE (employee_id);


--
-- Name: ict_staff ict_staff_pkey; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.ict_staff
    ADD CONSTRAINT ict_staff_pkey PRIMARY KEY (id);


--
-- Name: notifications_notification notifications_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.notifications_notification
    ADD CONSTRAINT notifications_notification_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: reservation_policy reservation_policy_pkey; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.reservation_policy
    ADD CONSTRAINT reservation_policy_pkey PRIMARY KEY (id);


--
-- Name: reservations reservations_pkey; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT reservations_pkey PRIMARY KEY (id);


--
-- Name: reservations_reservation reservations_reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.reservations_reservation
    ADD CONSTRAINT reservations_reservation_pkey PRIMARY KEY (id);


--
-- Name: room_amenities room_amenities_pkey; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.room_amenities
    ADD CONSTRAINT room_amenities_pkey PRIMARY KEY (id);


--
-- Name: rooms rooms_pkey; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_pkey PRIMARY KEY (id);


--
-- Name: rooms rooms_room_code_key; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_room_code_key UNIQUE (room_code);


--
-- Name: rooms_room rooms_room_pkey; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.rooms_room
    ADD CONSTRAINT rooms_room_pkey PRIMARY KEY (id);


--
-- Name: teachers teachers_employee_id_key; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_employee_id_key UNIQUE (employee_id);


--
-- Name: teachers teachers_pkey; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: rhen
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);


--
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: rhen
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


--
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: rhen
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);


--
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: rhen
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);


--
-- Name: accounts_user_username_6088629e_like; Type: INDEX; Schema: public; Owner: rhen
--

CREATE INDEX accounts_user_username_6088629e_like ON public.accounts_user USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: rhen
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: rhen
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: rhen
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: rhen
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: rhen
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: rhen
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: rhen
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: rhen
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: notifications_notification_reservation_id_b04baca7; Type: INDEX; Schema: public; Owner: rhen
--

CREATE INDEX notifications_notification_reservation_id_b04baca7 ON public.notifications_notification USING btree (reservation_id);


--
-- Name: notifications_notification_user_id_b5e8c0ff; Type: INDEX; Schema: public; Owner: rhen
--

CREATE INDEX notifications_notification_user_id_b5e8c0ff ON public.notifications_notification USING btree (user_id);


--
-- Name: reservations_reservation_room_id_f7d9ba76; Type: INDEX; Schema: public; Owner: rhen
--

CREATE INDEX reservations_reservation_room_id_f7d9ba76 ON public.reservations_reservation USING btree (room_id);


--
-- Name: reservations_reservation_user_id_6ed5b1c9; Type: INDEX; Schema: public; Owner: rhen
--

CREATE INDEX reservations_reservation_user_id_6ed5b1c9 ON public.reservations_reservation USING btree (user_id);


--
-- Name: accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: approvals approvals_approver_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.approvals
    ADD CONSTRAINT approvals_approver_id_fkey FOREIGN KEY (approver_id) REFERENCES public.users(id);


--
-- Name: approvals approvals_reservation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.approvals
    ADD CONSTRAINT approvals_reservation_id_fkey FOREIGN KEY (reservation_id) REFERENCES public.reservations(id) ON DELETE CASCADE;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ict_staff ict_staff_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.ict_staff
    ADD CONSTRAINT ict_staff_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: notifications_notification notifications_notifi_reservation_id_b04baca7_fk_reservati; Type: FK CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.notifications_notification
    ADD CONSTRAINT notifications_notifi_reservation_id_b04baca7_fk_reservati FOREIGN KEY (reservation_id) REFERENCES public.reservations_reservation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notifications_notification notifications_notification_user_id_b5e8c0ff_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.notifications_notification
    ADD CONSTRAINT notifications_notification_user_id_b5e8c0ff_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notifications notifications_reservation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_reservation_id_fkey FOREIGN KEY (reservation_id) REFERENCES public.reservations(id) ON DELETE CASCADE;


--
-- Name: notifications notifications_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: reservations reservations_requester_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT reservations_requester_id_fkey FOREIGN KEY (requester_id) REFERENCES public.users(id);


--
-- Name: reservations_reservation reservations_reservation_room_id_f7d9ba76_fk_rooms_room_id; Type: FK CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.reservations_reservation
    ADD CONSTRAINT reservations_reservation_room_id_f7d9ba76_fk_rooms_room_id FOREIGN KEY (room_id) REFERENCES public.rooms_room(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservations_reservation reservations_reservation_user_id_6ed5b1c9_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.reservations_reservation
    ADD CONSTRAINT reservations_reservation_user_id_6ed5b1c9_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservations reservations_room_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT reservations_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.rooms(id);


--
-- Name: room_amenities room_amenities_room_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.room_amenities
    ADD CONSTRAINT room_amenities_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.rooms(id) ON DELETE CASCADE;


--
-- Name: teachers teachers_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rhen
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: rhen
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


--
-- PostgreSQL database dump complete
--

\unrestrict x5CV4zBqTMvtoOiQxLeqIo4FbEeW4y2NtVtOG44UittKGW1iVe4GvpXcnYZlZnf

