// import { precacheAndRoute } from 'workbox-precaching';

// precacheAndRoute(self.__WB_MANIFEST);

// self.addEventListener('push', (event) => {
//   console.log('Push received');

//   let data = {
//     title: 'Notification',
//     body: 'Default message',
//     icon: '/icons/icon-192.png',
//   };

//   if (event.data) {
//     try {
//       // Try JSON first
//       data = event.data.json();
//     } catch (e) {
//       // Fallback for plain text (like DevTools push)
//       data.body = event.data.text();
//     }
//   }

//   event.waitUntil(
//     self.registration.showNotification(data.title, {
//       body: data.body,
//       icon: data.icon,
//       badge: '/icons/icon-192.png',
//     })
//   );
// });

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { createHandlerBoundToURL } from 'workbox-precaching';

// Precache all static assets (JS, CSS, HTML generated by Vite)
precacheAndRoute(self.__WB_MANIFEST);

// Clean up old caches from previous versions
cleanupOutdatedCaches();

// ─── App Shell (SPA navigation) ───────────────────────────────────────────────
// Any navigation request (page load) falls back to index.html when offline
const handler = createHandlerBoundToURL('/index.html');
const navigationRoute = new NavigationRoute(handler);
registerRoute(navigationRoute);

// ─── API Calls ────────────────────────────────────────────────────────────────
// Network first — tries to fetch fresh data, falls back to cache if offline
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,        // max 50 API responses cached
        maxAgeSeconds: 5 * 60, // cache for 5 minutes
      }),
    ],
  })
);

// ─── Images ───────────────────────────────────────────────────────────────────
// Cache first — images rarely change, serve from cache instantly
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'image-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 30,
        maxAgeSeconds: 7 * 24 * 60 * 60, // 7 days
      }),
    ],
  })
);

// ─── Static Assets (JS, CSS, Fonts) ───────────────────────────────────────────
// Stale while revalidate — serve cache instantly, update in background
registerRoute(
  ({ request }) =>
    request.destination === 'script' ||
    request.destination === 'style' ||
    request.destination === 'font',
  new StaleWhileRevalidate({
    cacheName: 'static-assets-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 30,
        maxAgeSeconds: 24 * 60 * 60, // 1 day
      }),
    ],
  })
);

// ─── Push Notifications ───────────────────────────────────────────────────────
self.addEventListener('push', (event) => {
  console.log('Push received');

  let data = {
    title: 'Notification',
    body: 'Default message',
    icon: '/icons/icon-192.png',
  };

  if (event.data) {
    try {
      data = event.data.json();
    } catch (e) {
      data.body = event.data.text();
    }
  }

  event.waitUntil(
    self.registration.showNotification(data.title, {
      body: data.body,
      icon: data.icon,
      badge: '/icons/icon-192.png',
    })
  );
});